<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>ecommerce-microservice</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>E-Commerce Microservice</name>
    <description>E-Commerce Microservices using Spring Boot and Spring Cloud</description>
    <!-- Child Modules -->
    <modules>
        <module>product-service</module>
        <module>order-service</module>
        <module>config-server</module>
        <module>web-gateway</module>
        <module>auth-service</module>
        <module>notification-service</module>
        <module>payment-service</module>
    </modules>

    <!-- Common Properties -->
    <properties>
        <java.version>21</java.version>

        <spring.boot.version>3.5.3</spring.boot.version>

        <!-- Use the Spring Cloud release compatible with your Spring Boot version -->
        <spring.cloud.version>2025.0.0</spring.cloud.version>

        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <!-- Import Spring Boot and Spring Cloud BOMs -->
    <dependencyManagement>

        <dependencies>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>

    </dependencyManagement>

    <!-- Common Plugin -->
    <build>

        <pluginManagement>

            <plugins>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.14.0</version>

                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                    </configuration>

                </plugin>

                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring.boot.version}</version>
                </plugin>

            </plugins>

        </pluginManagement>

    </build>

</project>